export const ROUTES = {
    HOMEPAGE_ROUTE: '/',
    LOGIN_ROUTE: '/login',
    REGISTER_ROUTE: '/register',
    FORGOT_PASSWORD_ROUTE: '/forgot-password',
    DASHBOARD_ROUTE: '/dashboard',
    CALENDAR_ROUTE: '/calendar',
    MAILS_ROUTE: '/mails',
    APARTMENTS_ROUTE: '/apartments',
    CLIENTS_ROUTE: '/clients',
    SETTINGS_ROUTE: '/settings',
    INFORMATION_ROUTE: '/information',
    CONNECTION_ROUTE: '/connection',
    PROFILE_ROUTE: '/profile',
};
